import { Client } from '@notionhq/client';
import { StudyMaterial } from '@/types';

/**
 * Extracts a normalized 32-character Notion UUID without hyphens
 * from either a raw ID, a hyphenated UUID, or a full Notion URL.
 * Example URLs:
 * https://www.notion.so/workspace/My-Page-Title-1234567890abcdef1234567890abcdef
 * https://notion.so/12345678-90ab-cdef-1234-567890abcdef
 */
export function extractNotionId(input: string): string {
  if (!input) return '';
  const trimmed = input.trim();
  // Check for 32-char hex at end of URL or standalone
  const match = trimmed.match(/[0-9a-fA-F]{32}/);
  if (match) return match[0];

  // Check for standard 36-char hyphenated UUID: 8-4-4-4-12
  const uuidMatch = trimmed.match(/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/);
  if (uuidMatch) {
    return uuidMatch[0].replace(/-/g, '');
  }

  // If already clean alphanumeric ID (32 chars)
  const clean = trimmed.replace(/[^0-9a-zA-Z]/g, '');
  if (clean.length === 32) return clean;

  return trimmed;
}

/**
 * Splits text into chunks of maximum 2000 characters to adhere to
 * the Notion API limit of 2,000 characters per text object.
 */
export function splitIntoNotionTextChunks(text: string, maxLength = 2000): Array<{ type: 'text'; text: { content: string } }> {
  if (!text) return [{ type: 'text', text: { content: '' } }];
  if (text.length <= maxLength) {
    return [{ type: 'text', text: { content: text } }];
  }

  const chunks: Array<{ type: 'text'; text: { content: string } }> = [];
  let remaining = text;
  while (remaining.length > 0) {
    const chunk = remaining.slice(0, maxLength);
    chunks.push({ type: 'text', text: { content: chunk } });
    remaining = remaining.slice(maxLength);
  }
  return chunks;
}

/**
 * Helper to build rich Notion block objects with safety limits.
 */
export function createNotionBlocks(material: StudyMaterial): any[] {
  const blocks: any[] = [];

  // 1. Header Banner Callout
  blocks.push({
    object: 'block',
    type: 'callout',
    callout: {
      icon: { type: 'emoji', emoji: '🎓' },
      rich_text: splitIntoNotionTextChunks(
        `Mosaic AI Multilingual Learning Hub\nSubject: ${material.subject} | Source: ${material.sourceLanguage.toUpperCase()} ➔ Target: ${material.targetLanguage.toUpperCase()}`
      ),
      color: 'purple_background',
    },
  });

  // 2. Bilingual Executive Summary
  const summaryText = material.content.translatedSummary || material.content.summary || 'Summary generated by Mosaic AI.';
  blocks.push({
    object: 'block',
    type: 'heading_2',
    heading_2: {
      rich_text: splitIntoNotionTextChunks(`💡 Bilingual Executive Summary (${material.targetLanguage.toUpperCase()})`),
    },
  });

  blocks.push({
    object: 'block',
    type: 'callout',
    callout: {
      icon: { type: 'emoji', emoji: '✨' },
      rich_text: splitIntoNotionTextChunks(summaryText),
      color: 'gray_background',
    },
  });

  if (material.content.simplifiedExplanation) {
    blocks.push({
      object: 'block',
      type: 'paragraph',
      paragraph: {
        rich_text: splitIntoNotionTextChunks(`Plain-Language Explanation: ${material.content.simplifiedExplanation}`),
      },
    });
  }

  if (material.content.feynmanAnalogy) {
    blocks.push({
      object: 'block',
      type: 'quote',
      quote: {
        rich_text: splitIntoNotionTextChunks(`🧠 Feynman Intuition: ${material.content.feynmanAnalogy}`),
      },
    });
  }

  // 3. Key Academic Takeaways
  const takeaways = material.content.translatedTakeaways || material.content.keyTakeaways || [];
  if (takeaways.length > 0) {
    blocks.push({
      object: 'block',
      type: 'heading_2',
      heading_2: {
        rich_text: splitIntoNotionTextChunks('📌 Key Study Takeaways'),
      },
    });

    for (const t of takeaways) {
      blocks.push({
        object: 'block',
        type: 'bulleted_list_item',
        bulleted_list_item: {
          rich_text: splitIntoNotionTextChunks(t),
        },
      });
    }
  }

  // 4. Bilingual Lecture Notes / Sections
  if (material.content.bilingualSections && material.content.bilingualSections.length > 0) {
    blocks.push({
      object: 'block',
      type: 'heading_2',
      heading_2: {
        rich_text: splitIntoNotionTextChunks(`🎙️ Bilingual Structured Notes (${material.targetLanguage.toUpperCase()})`),
      },
    });

    for (const sec of material.content.bilingualSections) {
      const headingText = `${sec.heading} ${sec.timestamp ? `(${sec.timestamp})` : ''}`;
      blocks.push({
        object: 'block',
        type: 'heading_3',
        heading_3: {
          rich_text: splitIntoNotionTextChunks(headingText),
        },
      });

      if (sec.headingTranslation) {
        blocks.push({
          object: 'block',
          type: 'paragraph',
          paragraph: {
            rich_text: splitIntoNotionTextChunks(`[${material.targetLanguage.toUpperCase()}] ${sec.headingTranslation}`),
          },
        });
      }

      blocks.push({
        object: 'block',
        type: 'toggle',
        toggle: {
          rich_text: splitIntoNotionTextChunks(`Study Notes (${material.targetLanguage.toUpperCase()} & Original)`),
          children: [
            {
              object: 'block',
              type: 'paragraph',
              paragraph: {
                rich_text: splitIntoNotionTextChunks(`Original (${material.sourceLanguage.toUpperCase()}): ${sec.originalText}`),
              },
            },
            {
              object: 'block',
              type: 'paragraph',
              paragraph: {
                rich_text: splitIntoNotionTextChunks(`Translation (${material.targetLanguage.toUpperCase()}): ${sec.translatedText}`),
              },
            },
            ...(sec.insightNotes
              ? [
                  {
                    object: 'block',
                    type: 'callout',
                    callout: {
                      icon: { type: 'emoji', emoji: '⚡' },
                      rich_text: splitIntoNotionTextChunks(`Instructor Insight: ${sec.insightNotes}`),
                    },
                  },
                ]
              : []),
          ],
        },
      });
    }
  }

  // 5. Bilingual Terminology & Glossaries
  if (material.content.bilingualGlossary && material.content.bilingualGlossary.length > 0) {
    blocks.push({
      object: 'block',
      type: 'heading_2',
      heading_2: {
        rich_text: splitIntoNotionTextChunks('📖 Bilingual Terminology & Glossaries'),
      },
    });

    for (const g of material.content.bilingualGlossary) {
      blocks.push({
        object: 'block',
        type: 'bulleted_list_item',
        bulleted_list_item: {
          rich_text: splitIntoNotionTextChunks(
            `${g.term} ➔ ${g.translation}: ${g.nativeExplanation || g.definition}`
          ),
        },
      });
    }
  }

  // 6. Revision Questions & Active Recall (Flashcards)
  const revQuestions = material.content.revisionQuestions || [];
  const flashcards = material.content.flashcards || [];

  if (revQuestions.length > 0 || flashcards.length > 0) {
    blocks.push({
      object: 'block',
      type: 'heading_2',
      heading_2: {
        rich_text: splitIntoNotionTextChunks('🧠 Revision Questions & Active Recall'),
      },
    });

    for (const q of revQuestions) {
      blocks.push({
        object: 'block',
        type: 'toggle',
        toggle: {
          rich_text: splitIntoNotionTextChunks(`Q: ${q.question} ${q.questionTranslation ? `(${q.questionTranslation})` : ''}`),
          children: [
            {
              object: 'block',
              type: 'paragraph',
              paragraph: {
                rich_text: splitIntoNotionTextChunks(`A: ${q.answer} ${q.answerTranslation ? `\n[${material.targetLanguage.toUpperCase()}]: ${q.answerTranslation}` : ''}`),
              },
            },
          ],
        },
      });
    }

    for (const fc of flashcards) {
      blocks.push({
        object: 'block',
        type: 'toggle',
        toggle: {
          rich_text: splitIntoNotionTextChunks(`Flashcard [${fc.difficulty.toUpperCase()}]: ${fc.question}`),
          children: [
            {
              object: 'block',
              type: 'paragraph',
              paragraph: {
                rich_text: splitIntoNotionTextChunks(`Question Translation (${material.targetLanguage.toUpperCase()}): ${fc.questionTranslation}`),
              },
            },
            {
              object: 'block',
              type: 'paragraph',
              paragraph: {
                rich_text: splitIntoNotionTextChunks(`Answer: ${fc.answer}\n[${material.targetLanguage.toUpperCase()}]: ${fc.answerTranslation}`),
              },
            },
          ],
        },
      });
    }
  }

  // 7. Assignment Breakdown Checklist & Rubric (if applicable)
  if (material.content.assignmentBreakdown) {
    const ab = material.content.assignmentBreakdown;
    blocks.push({
      object: 'block',
      type: 'heading_2',
      heading_2: {
        rich_text: splitIntoNotionTextChunks('📋 Milestone Action Plan & Grading Rubrics'),
      },
    });

    blocks.push({
      object: 'block',
      type: 'callout',
      callout: {
        icon: { type: 'emoji', emoji: '🎯' },
        rich_text: splitIntoNotionTextChunks(`Professor's Core Intent: ${ab.professorIntent}`),
      },
    });

    for (const milestone of ab.milestones) {
      blocks.push({
        object: 'block',
        type: 'heading_3',
        heading_3: {
          rich_text: splitIntoNotionTextChunks(`${milestone.phase}: ${milestone.title}`),
        },
      });

      for (const t of milestone.tasks) {
        blocks.push({
          object: 'block',
          type: 'to_do',
          to_do: {
            checked: t.done,
            rich_text: splitIntoNotionTextChunks(`${t.text} (${t.estimatedHours}h estimated)`),
          },
        });
      }
    }
  }

  // 8. Collapsible Original Transcript / Source Text
  if (material.content.rawSourceText) {
    const sourceChunks = splitIntoNotionTextChunks(material.content.rawSourceText.slice(0, 10000));
    blocks.push({
      object: 'block',
      type: 'toggle',
      toggle: {
        rich_text: splitIntoNotionTextChunks('📜 View Original Ingested Transcript / Source Text'),
        children: [
          {
            object: 'block',
            type: 'paragraph',
            paragraph: {
              rich_text: sourceChunks,
            },
          },
        ],
      },
    });
  }

  // 9. Footer Divider & Tagline
  blocks.push({
    object: 'block',
    type: 'divider',
    divider: {},
  });

  blocks.push({
    object: 'block',
    type: 'paragraph',
    paragraph: {
      rich_text: splitIntoNotionTextChunks(
        `Generated by Mosaic AI Multilingual Learning Companion • ${new Date().toLocaleDateString()}`
      ),
    },
  });

  return blocks;
}

/**
 * Creates a Notion page using the official Notion API client.
 * Handles database vs page parent, block batching (100 blocks limit),
 * and provides clear error diagnostics.
 */
export async function createNotionPage(
  material: StudyMaterial,
  options?: {
    apiKey?: string;
    parentType?: 'database' | 'page';
    parentId?: string;
  }
): Promise<{
  success: boolean;
  pageId: string;
  notionUrl: string;
  blocksCount: number;
  mode: 'live';
}> {
  const token = options?.apiKey || process.env.NOTION_API_KEY;
  if (!token) {
    throw new Error('Notion API key not configured. Please provide NOTION_API_KEY in your environment or Settings.');
  }

  // Determine parent ID: options > env database > env parent page
  const databaseId = process.env.NOTION_DATABASE_ID;
  const parentPageId = process.env.NOTION_PARENT_PAGE_ID;

  let resolvedParentId = options?.parentId;
  let resolvedParentType = options?.parentType;

  if (!resolvedParentId) {
    if (databaseId) {
      resolvedParentId = databaseId;
      resolvedParentType = 'database';
    } else if (parentPageId) {
      resolvedParentId = parentPageId;
      resolvedParentType = 'page';
    }
  }

  if (!resolvedParentId) {
    throw new Error(
      'No target Notion page or database ID specified. Set NOTION_DATABASE_ID or NOTION_PARENT_PAGE_ID in your environment or connection settings.'
    );
  }

  const cleanParentId = extractNotionId(resolvedParentId);
  const notion = new Client({ auth: token });
  const allBlocks = createNotionBlocks(material);

  // Notion API limit: max 100 blocks per request
  const initialBlocks = allBlocks.slice(0, 100);
  const subsequentBlocks = allBlocks.slice(100);

  let parentConfig: any;
  let propertiesConfig: any;

  if (resolvedParentType === 'database') {
    parentConfig = { database_id: cleanParentId };
    // Databases typically use "Name" or "Title" as the primary title property
    // We provide a standard title property
    propertiesConfig = {
      title: {
        title: splitIntoNotionTextChunks(material.title || 'Mosaic Study Notes'),
      },
    };
  } else {
    // Page parent
    parentConfig = { page_id: cleanParentId };
    propertiesConfig = {
      title: {
        title: splitIntoNotionTextChunks(material.title || 'Mosaic Study Notes'),
      },
    };
  }

  try {
    const createdPage = await notion.pages.create({
      parent: parentConfig,
      properties: propertiesConfig,
      children: initialBlocks,
      icon: {
        type: 'emoji',
        emoji: '🎓',
      },
    });

    const pageId = createdPage.id;
    // Notion page URL format: https://notion.so/<page_id_without_hyphens>
    const cleanId = pageId.replace(/-/g, '');
    const notionUrl = (createdPage as any).url || `https://notion.so/${cleanId}`;

    // Append any subsequent blocks in chunks of 100
    if (subsequentBlocks.length > 0) {
      for (let i = 0; i < subsequentBlocks.length; i += 100) {
        const batch = subsequentBlocks.slice(i, i + 100);
        await notion.blocks.children.append({
          block_id: pageId,
          children: batch,
        });
      }
    }

    return {
      success: true,
      pageId,
      notionUrl,
      blocksCount: allBlocks.length,
      mode: 'live',
    };
  } catch (error: any) {
    // Translate Notion API error codes to human-actionable advice
    const errorCode = error?.code || error?.status;
    const errorMessage = error?.message || 'Unknown error';

    if (errorCode === 'unauthorized' || error?.status === 401) {
      throw new Error(
        'Authentication failed (401 Unauthorized): The provided Notion API Key is invalid or expired. Check your NOTION_API_KEY secret token.'
      );
    }

    if (errorCode === 'object_not_found' || error?.status === 404 || error?.status === 403) {
      throw new Error(
        `Permission Denied (404/403): The Notion integration bot does not have access to target ID "${cleanParentId}". Open that page/database in Notion, click the "..." menu at the top right, select "Add connections" or "Connect to", and choose your integration bot.`
      );
    }

    if (errorCode === 'validation_error' || error?.status === 400) {
      throw new Error(
        `Notion Validation Error (400): ${errorMessage}. Verify that the target ID is a valid Notion Page or Database ID.`
      );
    }

    if (errorCode === 'rate_limited' || error?.status === 429) {
      throw new Error('Notion API rate limit reached (429). Please wait a few seconds and retry.');
    }

    throw new Error(`Notion API Error: ${errorMessage}`);
  }
}

/**
 * Tests live connection to Notion by querying users.me() and searching accessible objects.
 */
export async function testNotionConnection(apiKey?: string): Promise<{
  valid: boolean;
  botName?: string;
  workspaceName?: string;
  accessibleDatabases: Array<{ id: string; title: string; url: string }>;
  accessiblePages: Array<{ id: string; title: string; url: string }>;
  message: string;
}> {
  const token = apiKey || process.env.NOTION_API_KEY;
  if (!token) {
    return {
      valid: false,
      accessibleDatabases: [],
      accessiblePages: [],
      message: 'NOTION_API_KEY is not configured in the server environment or request.',
    };
  }

  try {
    const notion = new Client({ auth: token });
    const me = await notion.users.me();
    const botName = (me as any)?.name || 'Mosaic Notion Integration Bot';

    // Search for accessible pages & databases (limited to 10 for quick response)
    const searchResult = await notion.search({
      page_size: 10,
    });

    const accessibleDatabases: Array<{ id: string; title: string; url: string }> = [];
    const accessiblePages: Array<{ id: string; title: string; url: string }> = [];

    for (const item of searchResult.results as any[]) {
      const itemUrl = item.url || `https://notion.so/${item.id.replace(/-/g, '')}`;
      if (item.object === 'database' || item.object === 'data_source') {
        const titleArr = item.title || [];
        const titleText = titleArr.map((t: any) => t.plain_text).join('') || 'Untitled Database';
        accessibleDatabases.push({ id: item.id, title: titleText, url: itemUrl });
      } else if (item.object === 'page') {
        const props = item.properties || {};
        let titleText = 'Untitled Page';
        // Extract page title from properties
        for (const key of Object.keys(props)) {
          if (props[key]?.type === 'title') {
            titleText = props[key].title?.map((t: any) => t.plain_text).join('') || titleText;
            break;
          }
        }
        accessiblePages.push({ id: item.id, title: titleText, url: itemUrl });
      }
    }

    return {
      valid: true,
      botName,
      workspaceName: (me as any)?.bot?.workspace_name || undefined,
      accessibleDatabases,
      accessiblePages,
      message: `Successfully connected to Notion workspace as bot "${botName}". Found ${accessibleDatabases.length} database(s) and ${accessiblePages.length} shared page(s).`,
    };
  } catch (error: any) {
    return {
      valid: false,
      accessibleDatabases: [],
      accessiblePages: [],
      message: error.message || 'Failed to authenticate with Notion API.',
    };
  }
}

/**
 * Fetches page content from an existing Notion page (e.g. Notion AI Meeting Notes).
 * Reads blocks and extracts text for import into Mosaic.
 */
export async function fetchNotionPageContent(
  pageIdOrUrl: string,
  apiKey?: string
): Promise<{
  title: string;
  text: string;
  wordCount: number;
  pageUrl: string;
}> {
  const token = apiKey || process.env.NOTION_API_KEY;
  if (!token) {
    throw new Error('Notion API key required to fetch page content.');
  }

  const cleanId = extractNotionId(pageIdOrUrl);
  if (!cleanId) {
    throw new Error('Invalid Notion page URL or ID.');
  }

  const notion = new Client({ auth: token });

  // 1. Fetch Page Metadata
  const page = await notion.pages.retrieve({ page_id: cleanId });
  const props = (page as any).properties || {};
  let title = 'Imported Notion Document';
  for (const key of Object.keys(props)) {
    if (props[key]?.type === 'title') {
      title = props[key].title?.map((t: any) => t.plain_text).join('') || title;
      break;
    }
  }

  // 2. Fetch Child Blocks
  const blocksRes = await notion.blocks.children.list({
    block_id: cleanId,
    page_size: 100,
  });

  const extractedLines: string[] = [];

  for (const block of blocksRes.results as any[]) {
    const type = block.type;
    const contentObj = block[type];
    if (contentObj?.rich_text) {
      const lineText = contentObj.rich_text.map((rt: any) => rt.plain_text).join('');
      if (lineText.trim()) {
        if (type.startsWith('heading_1')) extractedLines.push(`\n# ${lineText}`);
        else if (type.startsWith('heading_2')) extractedLines.push(`\n## ${lineText}`);
        else if (type.startsWith('heading_3')) extractedLines.push(`\n### ${lineText}`);
        else if (type === 'bulleted_list_item') extractedLines.push(`- ${lineText}`);
        else if (type === 'numbered_list_item') extractedLines.push(`1. ${lineText}`);
        else if (type === 'to_do') extractedLines.push(`[${contentObj.checked ? 'x' : ' '}] ${lineText}`);
        else if (type === 'quote') extractedLines.push(`> ${lineText}`);
        else extractedLines.push(lineText);
      }
    }
  }

  const combinedText = extractedLines.join('\n').trim();
  const wordCount = combinedText.split(/\s+/).filter(Boolean).length;
  const pageUrl = (page as any).url || `https://notion.so/${cleanId}`;

  return {
    title,
    text: combinedText,
    wordCount,
    pageUrl,
  };
}

/**
 * Universal Markdown Fallback Generator for when Notion is not connected
 * or when the user prefers direct copy/paste.
 */
export function generateNotionMarkdown(material: StudyMaterial): string {
  const targetUpper = material.targetLanguage.toUpperCase();
  const sourceUpper = material.sourceLanguage.toUpperCase();

  const lines = [
    `# ${material.title}`,
    `**Subject:** ${material.subject} | **Source:** ${sourceUpper} | **Target:** ${targetUpper}`,
    `**Date:** ${new Date(material.createdAt).toLocaleDateString()}`,
    '',
    `> 💡 **Bilingual Executive Summary (${targetUpper})**`,
    `> ${material.content.translatedSummary || material.content.summary || 'Summary generated by Mosaic AI'}`,
    '',
  ];

  if (material.content.simplifiedExplanation) {
    lines.push(`**Plain-Language Explanation:** ${material.content.simplifiedExplanation}`, '');
  }

  if (material.content.feynmanAnalogy) {
    lines.push(`> 🧠 **Feynman Analogy:** ${material.content.feynmanAnalogy}`, '');
  }

  const takeaways = material.content.translatedTakeaways || material.content.keyTakeaways || [];
  if (takeaways.length > 0) {
    lines.push('## 📌 Key Study Takeaways');
    for (const t of takeaways) {
      lines.push(`- [x] ${t}`);
    }
    lines.push('');
  }

  if (material.content.bilingualGlossary && material.content.bilingualGlossary.length > 0) {
    lines.push('## 📖 Bilingual Terminology & Glossaries');
    lines.push('| Academic Term | Native Translation | Contextual Definition |');
    lines.push('| --- | --- | --- |');
    for (const g of material.content.bilingualGlossary) {
      lines.push(`| **${g.term}** | ${g.translation} | ${g.nativeExplanation || g.definition} |`);
    }
    lines.push('');
  }

  if (material.content.bilingualSections && material.content.bilingualSections.length > 0) {
    lines.push(`## 🎙️ Bilingual Lecture Notes (${targetUpper})`);
    for (const s of material.content.bilingualSections) {
      lines.push(`### ${s.heading} ${s.timestamp ? `(${s.timestamp})` : ''}`);
      if (s.headingTranslation) lines.push(`*${s.headingTranslation}*`);
      lines.push(`**Original (${sourceUpper}):** ${s.originalText}`);
      lines.push(`**${targetUpper}:** ${s.translatedText}`);
      if (s.insightNotes) lines.push(`> ⚡ **Instructor Insight:** ${s.insightNotes}`);
      lines.push('');
    }
  }

  const revQuestions = material.content.revisionQuestions || [];
  const flashcards = material.content.flashcards || [];
  if (revQuestions.length > 0 || flashcards.length > 0) {
    lines.push('## 🧠 Revision Questions & Active Recall');
    for (const q of revQuestions) {
      lines.push(`- **Q:** ${q.question} ${q.questionTranslation ? `*(${q.questionTranslation})*` : ''}`);
      lines.push(`  - **A:** ${q.answer} ${q.answerTranslation ? `*[${targetUpper}]: ${q.answerTranslation}*` : ''}`);
    }
    for (const fc of flashcards) {
      lines.push(`- **Flashcard [${fc.difficulty}]:** ${fc.question}`);
      lines.push(`  - **${targetUpper}:** ${fc.questionTranslation}`);
      lines.push(`  - **Answer:** ${fc.answer} (${fc.answerTranslation})`);
    }
    lines.push('');
  }

  if (material.content.assignmentBreakdown) {
    const ab = material.content.assignmentBreakdown;
    lines.push('## 📋 Actionable Milestones & Checklist');
    lines.push(`> 🎯 **Professor Intent:** ${ab.professorIntent}`, '');
    for (const m of ab.milestones) {
      lines.push(`### ${m.phase}: ${m.title}`);
      for (const t of m.tasks) {
        lines.push(`- [${t.done ? 'x' : ' '}] ${t.text} (${t.estimatedHours}h)`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Synced via Mosaic AI — Multilingual Learning Companion for Notion*');

  return lines.join('\n');
}
