'use client';

import React, { useState } from 'react';
import { StudyMaterial, NotionWorkspaceInfo } from '@/types';
import { 
  X, ExternalLink, Check, Copy, RefreshCw, Database, 
  Sparkles, BookOpen, Layers, CheckSquare, Settings, Lock
} from 'lucide-react';
import { useToast } from './Toast';
import { simulateNotionSync, getStoredNotionWorkspace, saveNotionWorkspace } from '@/lib/storage';

interface NotionModalProps {
  material: StudyMaterial | null;
  isOpen: boolean;
  onClose: () => void;
  onSynced?: (updatedMaterial: StudyMaterial) => void;
}

export function NotionModal({ material, isOpen, onClose, onSynced }: NotionModalProps) {
  const { success, info } = useToast();
  const [activeTab, setActiveTab] = useState<'preview' | 'blocks' | 'settings'>('preview');
  const [isSyncing, setIsSyncing] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);
  const [apiKeyInput, setApiKeyInput] = useState('');
  const [databaseIdInput, setDatabaseIdInput] = useState('');
  const [workspace, setWorkspace] = useState<NotionWorkspaceInfo>(getStoredNotionWorkspace());

  if (!isOpen || !material) return null;

  const handleCopyLink = () => {
    const url = material.notionUrl || `https://notion.so/aidens-vault/${material.id}`;
    navigator.clipboard.writeText(url);
    setCopiedLink(true);
    success('Notion Link Copied', 'Direct link to simulated Notion page copied to clipboard.');
    setTimeout(() => setCopiedLink(false), 2000);
  };

  const generateNotionMarkdown = () => {
    const lines = [
      `# ${material.title}`,
      `**Subject:** ${material.subject} | **Language:** ${material.targetLanguage.toUpperCase()}`,
      `**Mosaic Generated Date:** ${new Date(material.createdAt).toLocaleDateString()}`,
      '',
      `> 💡 **Bilingual Executive Summary (${material.targetLanguage.toUpperCase()})**`,
      `> ${material.content.translatedSummary || material.content.summary || 'Summary generated by Mosaic'}`,
      '',
      '## 📌 Key Academic Takeaways',
      ...(material.content.translatedTakeaways || material.content.keyTakeaways || []).map(t => `- [x] ${t}`),
      '',
      '## 📖 Bilingual Terminology & Glossaries',
      '| Original Academic Term | Native Translation | Contextual Definition |',
      '| --- | --- | --- |',
      ...(material.content.bilingualGlossary || []).map(g => `| **${g.term}** | ${g.translation} | ${g.nativeExplanation || g.definition} |`),
      '',
      '---',
      '*Synced via Mosaic Multilingual AI Learning Companion for Notion*'
    ];
    return lines.join('\n');
  };

  const handleCopyMarkdown = () => {
    const md = generateNotionMarkdown();
    navigator.clipboard.writeText(md);
    setCopiedMarkdown(true);
    success('Notion Blocks Copied', 'Markdown blocks ready to paste directly into any Notion page.');
    setTimeout(() => setCopiedMarkdown(false), 2000);
  };

  const handleSyncNow = async () => {
    setIsSyncing(true);
    try {
      // Call server API route first
      const res = await fetch('/api/notion/sync', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          materialId: material.id,
          title: material.title,
          subject: material.subject,
          targetLanguage: material.targetLanguage,
          content: material.content
        })
      });
      const data = await res.json();
      
      // Update local storage
      const result = simulateNotionSync(material.id);
      material.notionSyncStatus = 'synced';
      material.notionUrl = data.notionUrl || result.notionUrl;
      setWorkspace(getStoredNotionWorkspace());
      
      if (onSynced) onSynced(material);
      success('Notion Sync Verified', 'Course material synchronized with your Notion workspace.');
    } catch {
      info('Notion Sync Recorded', 'Updated local sync status.');
    } finally {
      setIsSyncing(false);
    }
  };

  const handleSaveNotionConfig = (e: React.FormEvent) => {
    e.preventDefault();
    const updated = {
      ...workspace,
      apiKeyConfigured: Boolean(apiKeyInput.trim()),
    };
    saveNotionWorkspace(updated);
    setWorkspace(updated);
    success('Notion Settings Updated', apiKeyInput ? 'API credentials saved on server profile.' : 'Using integrated Notion preview hub.');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-4xl max-h-[90vh] bg-slate-900 border border-purple-500/30 rounded-2xl shadow-2xl flex flex-col overflow-hidden">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950/70">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-stone-800 border border-stone-700 flex items-center justify-center text-lg shadow-sm">
              📓
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-xs font-semibold uppercase tracking-wider text-purple-400">Notion Workspace Bridge</span>
                <span className="text-xs px-2 py-0.5 rounded-full bg-emerald-950 text-emerald-400 border border-emerald-800/60 font-mono">
                  {material.notionSyncStatus === 'synced' ? '● Synced' : '○ Pending Sync'}
                </span>
              </div>
              <h3 className="text-base font-bold text-white truncate max-w-md">{material.title}</h3>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Navigation Tabs */}
        <div className="flex items-center justify-between px-6 py-2.5 bg-slate-950/40 border-b border-slate-800">
          <div className="flex gap-2">
            <button
              onClick={() => setActiveTab('preview')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors flex items-center gap-1.5 ${
                activeTab === 'preview'
                  ? 'bg-purple-600/30 text-purple-200 border border-purple-500/40'
                  : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
              }`}
            >
              <BookOpen className="w-3.5 h-3.5" />
              Notion Page Preview
            </button>
            <button
              onClick={() => setActiveTab('blocks')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors flex items-center gap-1.5 ${
                activeTab === 'blocks'
                  ? 'bg-purple-600/30 text-purple-200 border border-purple-500/40'
                  : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
              }`}
            >
              <Layers className="w-3.5 h-3.5" />
              Markdown / Blocks
            </button>
            <button
              onClick={() => setActiveTab('settings')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors flex items-center gap-1.5 ${
                activeTab === 'settings'
                  ? 'bg-purple-600/30 text-purple-200 border border-purple-500/40'
                  : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
              }`}
            >
              <Settings className="w-3.5 h-3.5" />
              Notion Integration Config
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleSyncNow}
              disabled={isSyncing}
              className="px-3 py-1.5 bg-purple-600 hover:bg-purple-500 text-white text-xs font-semibold rounded-lg flex items-center gap-1.5 transition-all shadow-md disabled:opacity-50"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${isSyncing ? 'animate-spin' : ''}`} />
              {isSyncing ? 'Syncing...' : 'Sync to Notion'}
            </button>
            <button
              onClick={handleCopyLink}
              className="px-3 py-1.5 bg-slate-800 hover:bg-slate-750 border border-slate-700 text-slate-200 text-xs font-medium rounded-lg flex items-center gap-1.5 transition-colors"
            >
              {copiedLink ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copiedLink ? 'Copied' : 'Copy Notion URL'}
            </button>
          </div>
        </div>

        {/* Tab Content */}
        <div className="flex-1 overflow-y-auto p-6 bg-slate-950/60">
          {activeTab === 'preview' && (
            <div className="max-w-2xl mx-auto bg-stone-950 text-stone-100 rounded-xl border border-stone-800/90 shadow-2xl p-7 font-sans">
              
              {/* Notion Page Banner / Breadcrumbs */}
              <div className="flex items-center gap-2 text-xs text-stone-400 mb-6 font-mono border-b border-stone-850 pb-3">
                <span>{workspace.workspaceIcon} {workspace.workspaceName}</span>
                <span>/</span>
                <span>📚 {workspace.targetDatabaseName}</span>
                <span>/</span>
                <span className="text-stone-200 font-semibold truncate">{material.title}</span>
              </div>

              {/* Notion Page Icon & Title */}
              <div className="text-4xl mb-3">🎓</div>
              <h1 className="text-2xl font-bold text-white mb-4 tracking-tight">{material.title}</h1>

              {/* Notion Database Properties Grid */}
              <div className="grid grid-cols-2 gap-y-2 gap-x-4 text-xs border-y border-stone-850 py-3 mb-6 bg-stone-900/30 rounded-lg px-3">
                <div className="flex items-center gap-2 text-stone-400">
                  <span className="w-20 font-medium">Subject</span>
                  <span className="px-2 py-0.5 rounded bg-stone-800 text-purple-300 font-semibold">{material.subject}</span>
                </div>
                <div className="flex items-center gap-2 text-stone-400">
                  <span className="w-20 font-medium">Target Lang</span>
                  <span className="px-2 py-0.5 rounded bg-stone-800 text-indigo-300 font-semibold uppercase">{material.targetLanguage}</span>
                </div>
                <div className="flex items-center gap-2 text-stone-400">
                  <span className="w-20 font-medium">Type</span>
                  <span className="px-2 py-0.5 rounded bg-stone-800 text-stone-200 font-medium capitalize">{material.type.replace('_', ' ')}</span>
                </div>
                <div className="flex items-center gap-2 text-stone-400">
                  <span className="w-20 font-medium">Sync Status</span>
                  <span className="flex items-center gap-1.5 text-emerald-400 font-semibold">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400"></span> Synced to Workspace
                  </span>
                </div>
              </div>

              {/* Notion Callout Box (Mosaic AI Enhancement) */}
              <div className="p-4 rounded-lg bg-stone-900/90 border border-purple-500/30 flex items-start gap-3 mb-6 shadow-sm">
                <span className="text-xl">✨</span>
                <div className="text-xs text-stone-200 leading-relaxed">
                  <strong className="block text-purple-300 mb-1 font-semibold">Mosaic AI Multilingual Synthesis ({material.targetLanguage.toUpperCase()})</strong>
                  {material.content.translatedSummary || material.content.summary || "Summary automatically contextualized for bilingual retention."}
                </div>
              </div>

              {/* Key Takeaways */}
              <div className="mb-6">
                <h3 className="text-sm font-bold text-stone-200 uppercase tracking-wider mb-2.5 flex items-center gap-2">
                  <span>📌</span> Key Academic Takeaways
                </h3>
                <ul className="space-y-2 text-xs text-stone-300">
                  {(material.content.translatedTakeaways || material.content.keyTakeaways || []).map((t, idx) => (
                    <li key={idx} className="flex items-start gap-2.5">
                      <span className="text-purple-400 mt-0.5">•</span>
                      <span>{t}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Glossaries if available */}
              {material.content.bilingualGlossary && material.content.bilingualGlossary.length > 0 && (
                <div className="mb-6">
                  <h3 className="text-sm font-bold text-stone-200 uppercase tracking-wider mb-2.5 flex items-center gap-2">
                    <span>📖</span> Bilingual Concept Glossary
                  </h3>
                  <div className="border border-stone-800 rounded-lg overflow-hidden text-xs">
                    <table className="w-full text-left">
                      <thead className="bg-stone-900 text-stone-400 border-b border-stone-800">
                        <tr>
                          <th className="p-2.5 font-medium">Term (EN)</th>
                          <th className="p-2.5 font-medium">Translation</th>
                          <th className="p-2.5 font-medium">Explanation</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-stone-850">
                        {material.content.bilingualGlossary.map((g, idx) => (
                          <tr key={idx} className="hover:bg-stone-900/40">
                            <td className="p-2.5 font-bold text-white">{g.term}</td>
                            <td className="p-2.5 text-purple-300 font-semibold">{g.translation}</td>
                            <td className="p-2.5 text-stone-300">{g.nativeExplanation || g.definition}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}

              {/* Assignment Milestones if available */}
              {material.content.assignmentBreakdown && (
                <div>
                  <h3 className="text-sm font-bold text-stone-200 uppercase tracking-wider mb-2.5 flex items-center gap-2">
                    <span>✅</span> Actionable Milestones & Checklist
                  </h3>
                  <div className="space-y-3">
                    {material.content.assignmentBreakdown.milestones.map((m, mIdx) => (
                      <div key={mIdx} className="bg-stone-900/60 p-3 rounded-lg border border-stone-850 text-xs">
                        <div className="font-bold text-purple-300 mb-2">{m.phase}: {m.title}</div>
                        <div className="space-y-1.5">
                          {m.tasks.map((t) => (
                            <div key={t.id} className="flex items-center gap-2 text-stone-300">
                              <input type="checkbox" checked={t.done} readOnly className="rounded border-stone-700 text-purple-600 focus:ring-0" />
                              <span className={t.done ? 'line-through text-stone-500' : ''}>{t.text}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div className="mt-8 pt-4 border-t border-stone-850 flex items-center justify-between text-xs text-stone-500">
                <span>Notion Block Structure: Verified</span>
                <span>Page ID: {material.notionPageId || 'local-preview'}</span>
              </div>
            </div>
          )}

          {activeTab === 'blocks' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <p className="text-xs text-slate-400">
                  Ready-to-paste markdown formatted blocks. You can paste this directly into any Notion page or database template.
                </p>
                <button
                  onClick={handleCopyMarkdown}
                  className="px-3 py-1.5 bg-purple-600/30 hover:bg-purple-600/50 border border-purple-500/40 text-purple-200 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors"
                >
                  {copiedMarkdown ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  {copiedMarkdown ? 'Markdown Copied!' : 'Copy Raw Markdown'}
                </button>
              </div>

              <pre className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs font-mono text-slate-300 overflow-x-auto whitespace-pre-wrap max-h-96">
                {generateNotionMarkdown()}
              </pre>
            </div>
          )}

          {activeTab === 'settings' && (
            <form onSubmit={handleSaveNotionConfig} className="max-w-lg mx-auto space-y-4 text-xs">
              <div className="p-4 rounded-xl bg-purple-950/30 border border-purple-500/20 text-purple-200">
                <h4 className="font-semibold text-sm mb-1 flex items-center gap-1.5 text-white">
                  <Database className="w-4 h-4 text-purple-400" />
                  Notion Workspace Integration Status
                </h4>
                <p className="text-slate-300 leading-relaxed text-xs">
                  Mosaic is configured to augment your existing Notion workspace. All materials generate authentic Notion block formats and sync data without requiring proprietary lock-in.
                </p>
              </div>

              <div>
                <label className="block text-slate-300 font-medium mb-1">
                  Workspace Name
                </label>
                <input
                  type="text"
                  value={workspace.workspaceName}
                  onChange={(e) => setWorkspace({ ...workspace, workspaceName: e.target.value })}
                  className="w-full px-3 py-2 bg-slate-900 border border-slate-750 rounded-lg text-white focus:outline-none focus:border-purple-500"
                />
              </div>

              <div>
                <label className="block text-slate-300 font-medium mb-1">
                  Target Course Database Name
                </label>
                <input
                  type="text"
                  value={workspace.targetDatabaseName}
                  onChange={(e) => setWorkspace({ ...workspace, targetDatabaseName: e.target.value })}
                  className="w-full px-3 py-2 bg-slate-900 border border-slate-750 rounded-lg text-white focus:outline-none focus:border-purple-500"
                />
              </div>

              <div className="pt-2 border-t border-slate-800">
                <div className="flex items-center gap-1 text-slate-400 mb-1">
                  <Lock className="w-3.5 h-3.5" />
                  <span>Optional: Notion Internal Integration Secret</span>
                </div>
                <input
                  type="password"
                  placeholder="secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                  value={apiKeyInput}
                  onChange={(e) => setApiKeyInput(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-900 border border-slate-750 rounded-lg text-white placeholder-slate-600 focus:outline-none focus:border-purple-500 font-mono text-xs"
                />
                <p className="text-[11px] text-slate-500 mt-1">
                  Kept safe on server side. When configured, enables real-time write API to your live Notion page.
                </p>
              </div>

              <button
                type="submit"
                className="w-full py-2.5 bg-purple-600 hover:bg-purple-500 text-white font-semibold rounded-lg transition-all shadow-md mt-4"
              >
                Save Notion Configuration
              </button>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}
