'use client';

import React, { useState, useEffect } from 'react';
import { StudyMaterial, NotionWorkspaceInfo } from '@/types';
import { 
  X, Check, Copy, RefreshCw, Database, 
  BookOpen, Layers, Settings, Lock, Link2, Unlink
} from 'lucide-react';
import { useToast } from './Toast';
import { 
  simulateNotionSync, 
  getStoredNotionWorkspace, 
  saveNotionWorkspace,
  connectNotionWorkspace,
  disconnectNotionWorkspace
} from '@/lib/storage';

interface NotionModalProps {
  material?: StudyMaterial | null;
  isOpen: boolean;
  onClose: () => void;
  onSynced?: (updatedMaterial: StudyMaterial) => void;
}

export function NotionModal({ material, isOpen, onClose, onSynced }: NotionModalProps) {
  const { success, info } = useToast();
  const [workspace, setWorkspace] = useState<NotionWorkspaceInfo>(getStoredNotionWorkspace());
  const [activeTab, setActiveTab] = useState<'preview' | 'blocks' | 'settings'>('preview');
  const [isSyncing, setIsSyncing] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);
  const [workspaceNameInput, setWorkspaceNameInput] = useState('');
  const [databaseNameInput, setDatabaseNameInput] = useState('');
  const [apiKeyInput, setApiKeyInput] = useState('');

  useEffect(() => {
    if (isOpen) {
      const ws = getStoredNotionWorkspace();
      setWorkspace(ws);
      setWorkspaceNameInput(ws.workspaceName || 'My Academic Vault');
      setDatabaseNameInput(ws.targetDatabaseName || 'Courses & Notes 2026');
      if (!ws.connected) {
        setActiveTab('settings');
      }
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleCopyLink = () => {
    const url = material?.notionUrl || `https://notion.so/workspace/${material?.id || 'demo'}`;
    navigator.clipboard.writeText(url);
    setCopiedLink(true);
    success('Notion Link Copied', 'Direct link to Notion page copied.');
    setTimeout(() => setCopiedLink(false), 2000);
  };

  const generateNotionMarkdown = () => {
    if (!material) return '# Mosaic Study Material\nConnect to Notion to sync notes.';
    const lines = [
      `# ${material.title}`,
      `**Subject:** ${material.subject} | **Language:** ${material.targetLanguage.toUpperCase()}`,
      `**Mosaic Generated Date:** ${new Date(material.createdAt).toLocaleDateString()}`,
      '',
      `> 💡 **Bilingual Executive Summary (${material.targetLanguage.toUpperCase()})**`,
      `> ${material.content.translatedSummary || material.content.summary || 'Summary generated by Mosaic'}`,
      '',
      '## 📌 Key Academic Takeaways',
      ...(material.content.translatedTakeaways || material.content.keyTakeaways || []).map(t => `- [x] ${t}`),
      '',
      '## 📖 Bilingual Terminology & Glossaries',
      '| Original Academic Term | Native Translation | Contextual Definition |',
      '| --- | --- | --- |',
      ...(material.content.bilingualGlossary || []).map(g => `| **${g.term}** | ${g.translation} | ${g.nativeExplanation || g.definition} |`),
      '',
      '---',
      '*Exported via Mosaic Multilingual AI Learning Companion for Notion*'
    ];
    return lines.join('\n');
  };

  const handleCopyMarkdown = () => {
    const md = generateNotionMarkdown();
    navigator.clipboard.writeText(md);
    setCopiedMarkdown(true);
    success('Notion Blocks Copied', 'Markdown blocks ready to paste directly into Notion.');
    setTimeout(() => setCopiedMarkdown(false), 2000);
  };

  const handleConnectNotion = (e: React.FormEvent) => {
    e.preventDefault();
    const updated = connectNotionWorkspace(workspaceNameInput, databaseNameInput, apiKeyInput);
    setWorkspace(updated);
    success('Notion Connected', `Connected to workspace "${updated.workspaceName}".`);
    if (material) {
      setActiveTab('preview');
    }
  };

  const handleDisconnectNotion = () => {
    const updated = disconnectNotionWorkspace();
    setWorkspace(updated);
    info('Notion Disconnected', 'Your workspace connection has been removed.');
  };

  const handleSyncNow = async () => {
    if (!workspace.connected) {
      setActiveTab('settings');
      info('Connect Required', 'Please connect your Notion workspace before syncing.');
      return;
    }
    if (!material) return;

    setIsSyncing(true);
    try {
      await fetch('/api/notion/sync', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          materialId: material.id,
          title: material.title,
          subject: material.subject,
          targetLanguage: material.targetLanguage,
          content: material.content
        })
      });

      const result = simulateNotionSync(material.id);
      material.notionSyncStatus = 'synced';
      material.notionUrl = result.notionUrl;
      setWorkspace(getStoredNotionWorkspace());

      if (onSynced) onSynced(material);
      success('Notion Sync Verified', 'Synchronized with your Notion workspace.');
    } catch {
      info('Notion Sync Recorded', 'Updated local sync status.');
    } finally {
      setIsSyncing(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-3xl max-h-[90vh] bg-black border border-zinc-800 rounded-2xl shadow-2xl flex flex-col overflow-hidden text-white">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-zinc-850 bg-zinc-950">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-zinc-900 border border-zinc-800 flex items-center justify-center text-base shadow-sm">
              📓
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-xs font-semibold uppercase tracking-wider text-orange-400">
                  Notion Workspace Integration
                </span>
                <span
                  className={`text-[10px] px-2 py-0.5 rounded-full font-mono ${
                    workspace.connected
                      ? 'bg-emerald-950 text-emerald-400 border border-emerald-800/60'
                      : 'bg-zinc-900 text-zinc-400 border border-zinc-800'
                  }`}
                >
                  {workspace.connected ? '● Connected' : '○ Not Connected'}
                </span>
              </div>
              <h3 className="text-sm font-bold text-white truncate max-w-md">
                {material ? material.title : (workspace.workspaceName || 'Notion Integration Setup')}
              </h3>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-zinc-400 hover:text-white hover:bg-zinc-900 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Navigation Tabs */}
        <div className="flex items-center justify-between px-6 py-2.5 bg-zinc-950 border-b border-zinc-850">
          <div className="flex gap-2">
            <button
              onClick={() => setActiveTab('preview')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors flex items-center gap-1.5 ${
                activeTab === 'preview'
                  ? 'bg-orange-600/20 text-orange-300 border border-orange-500/40'
                  : 'text-zinc-400 hover:text-white hover:bg-zinc-900'
              }`}
            >
              <BookOpen className="w-3.5 h-3.5" />
              Notion Page Preview
            </button>
            <button
              onClick={() => setActiveTab('blocks')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors flex items-center gap-1.5 ${
                activeTab === 'blocks'
                  ? 'bg-orange-600/20 text-orange-300 border border-orange-500/40'
                  : 'text-zinc-400 hover:text-white hover:bg-zinc-900'
              }`}
            >
              <Layers className="w-3.5 h-3.5" />
              Markdown Blocks
            </button>
            <button
              onClick={() => setActiveTab('settings')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors flex items-center gap-1.5 ${
                activeTab === 'settings'
                  ? 'bg-orange-600/20 text-orange-300 border border-orange-500/40'
                  : 'text-zinc-400 hover:text-white hover:bg-zinc-900'
              }`}
            >
              <Settings className="w-3.5 h-3.5" />
              Connection Settings
            </button>
          </div>

          {material && (
            <div className="flex items-center gap-2">
              <button
                onClick={handleSyncNow}
                disabled={isSyncing}
                className="px-3 py-1.5 bg-orange-600 hover:bg-orange-500 text-white text-xs font-semibold rounded-lg flex items-center gap-1.5 transition-all shadow-md disabled:opacity-50"
              >
                <RefreshCw className={`w-3.5 h-3.5 ${isSyncing ? 'animate-spin' : ''}`} />
                {isSyncing ? 'Syncing...' : 'Sync to Notion'}
              </button>
            </div>
          )}
        </div>

        {/* Tab Content */}
        <div className="flex-1 overflow-y-auto p-6 bg-black">
          {activeTab === 'preview' && (
            <div>
              {!workspace.connected && (
                <div className="mb-6 p-4 rounded-xl bg-zinc-900/90 border border-orange-500/40 flex items-center justify-between gap-4">
                  <div>
                    <div className="font-semibold text-white text-xs">Notion is not connected</div>
                    <div className="text-[11px] text-zinc-400 mt-0.5">
                      Connect your Notion workspace to enable automatic synchronization of course notes.
                    </div>
                  </div>
                  <button
                    onClick={() => setActiveTab('settings')}
                    className="px-3 py-1.5 bg-orange-600 hover:bg-orange-500 text-white rounded-lg text-xs font-semibold shrink-0 transition-colors"
                  >
                    Connect Notion Now
                  </button>
                </div>
              )}

              {material ? (
                <div className="max-w-2xl mx-auto bg-zinc-950 text-zinc-100 rounded-xl border border-zinc-850 p-6 font-sans">
                  {/* Notion Page Breadcrumbs */}
                  <div className="flex items-center gap-2 text-xs text-zinc-400 mb-5 font-mono border-b border-zinc-850 pb-3">
                    <span>{workspace.workspaceIcon || '📓'} {workspace.connected ? workspace.workspaceName : 'Notion Workspace (Offline)'}</span>
                    <span>/</span>
                    <span>📚 {workspace.connected ? workspace.targetDatabaseName : 'Course Notes'}</span>
                    <span>/</span>
                    <span className="text-zinc-200 font-semibold truncate">{material.title}</span>
                  </div>

                  <div className="text-3xl mb-3">🎓</div>
                  <h1 className="text-xl font-bold text-white mb-4 tracking-tight">{material.title}</h1>

                  {/* Notion Database Properties */}
                  <div className="grid grid-cols-2 gap-y-2 gap-x-4 text-xs border-y border-zinc-850 py-3 mb-6 bg-zinc-900/50 rounded-lg px-3">
                    <div className="flex items-center gap-2 text-zinc-400">
                      <span className="w-20 font-medium">Subject</span>
                      <span className="px-2 py-0.5 rounded bg-zinc-800 text-orange-300 font-semibold">{material.subject}</span>
                    </div>
                    <div className="flex items-center gap-2 text-zinc-400">
                      <span className="w-20 font-medium">Target Lang</span>
                      <span className="px-2 py-0.5 rounded bg-zinc-800 text-zinc-200 font-semibold uppercase">{material.targetLanguage}</span>
                    </div>
                    <div className="flex items-center gap-2 text-zinc-400">
                      <span className="w-20 font-medium">Sync Status</span>
                      <span className={`flex items-center gap-1.5 font-semibold ${material.notionSyncStatus === 'synced' ? 'text-emerald-400' : 'text-zinc-400'}`}>
                        <span className={`w-1.5 h-1.5 rounded-full ${material.notionSyncStatus === 'synced' ? 'bg-emerald-400' : 'bg-zinc-500'}`} />
                        {material.notionSyncStatus === 'synced' ? 'Synced to Notion' : 'Local Draft (Pending)'}
                      </span>
                    </div>
                  </div>

                  {/* Notion Callout Box */}
                  <div className="p-4 rounded-lg bg-zinc-900 border border-orange-500/30 flex items-start gap-3 mb-5">
                    <span className="text-lg">💡</span>
                    <div className="text-xs text-zinc-200 leading-relaxed">
                      <strong className="block text-orange-400 mb-1 font-semibold">
                        Mosaic AI Multilingual Summary ({material.targetLanguage.toUpperCase()})
                      </strong>
                      {material.content.translatedSummary || material.content.summary}
                    </div>
                  </div>

                  {/* Key Takeaways */}
                  <div className="mb-5">
                    <h3 className="text-xs font-bold text-zinc-300 uppercase tracking-wider mb-2">
                      📌 Key Academic Takeaways
                    </h3>
                    <ul className="space-y-1.5 text-xs text-zinc-300">
                      {(material.content.translatedTakeaways || material.content.keyTakeaways || []).map((t, idx) => (
                        <li key={idx} className="flex items-start gap-2">
                          <span className="text-orange-400 mt-0.5">•</span>
                          <span>{t}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Footer actions */}
                  <div className="pt-4 border-t border-zinc-850 flex items-center justify-between text-xs text-zinc-500">
                    <span>Block Structure: Verified Notion Format</span>
                    <button
                      onClick={handleCopyLink}
                      className="text-orange-400 hover:underline flex items-center gap-1"
                    >
                      {copiedLink ? 'Copied URL' : 'Copy Notion Page URL'}
                    </button>
                  </div>
                </div>
              ) : (
                <div className="text-center p-8 text-zinc-400 text-xs">
                  No material selected for preview. Use the settings tab to configure your Notion connection.
                </div>
              )}
            </div>
          )}

          {activeTab === 'blocks' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <p className="text-xs text-zinc-400">
                  Ready-to-paste markdown blocks formatted for Notion.
                </p>
                <button
                  onClick={handleCopyMarkdown}
                  className="px-3 py-1.5 bg-orange-600 hover:bg-orange-500 text-white rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors"
                >
                  {copiedMarkdown ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  {copiedMarkdown ? 'Markdown Copied!' : 'Copy Markdown Blocks'}
                </button>
              </div>

              <pre className="p-4 rounded-xl bg-zinc-950 border border-zinc-800 text-xs font-mono text-zinc-300 overflow-x-auto whitespace-pre-wrap max-h-96">
                {generateNotionMarkdown()}
              </pre>
            </div>
          )}

          {activeTab === 'settings' && (
            <div className="max-w-md mx-auto space-y-5 text-xs">
              <div className="p-4 rounded-xl bg-zinc-900 border border-zinc-800">
                <div className="flex items-center justify-between mb-2">
                  <div className="font-semibold text-white text-sm flex items-center gap-2">
                    <Database className="w-4 h-4 text-orange-400" />
                    <span>Notion Workspace Option</span>
                  </div>
                  <span
                    className={`text-[10px] px-2 py-0.5 rounded-full font-medium ${
                      workspace.connected
                        ? 'bg-emerald-950 text-emerald-400 border border-emerald-800'
                        : 'bg-zinc-800 text-zinc-400'
                    }`}
                  >
                    {workspace.connected ? 'Connected' : 'Disconnected'}
                  </span>
                </div>
                <p className="text-zinc-400 text-xs leading-relaxed">
                  Connecting to Notion is completely optional. When connected, Mosaic pushes translated lecture summaries, flashcard packs, and assignment checklists directly to your database.
                </p>
              </div>

              <form onSubmit={handleConnectNotion} className="space-y-4">
                <div>
                  <label className="block text-zinc-300 font-medium mb-1">
                    Notion Workspace Name
                  </label>
                  <input
                    type="text"
                    placeholder="e.g. Stanford Academic Vault 2026"
                    value={workspaceNameInput}
                    onChange={(e) => setWorkspaceNameInput(e.target.value)}
                    className="w-full px-3 py-2 bg-zinc-900 border border-zinc-800 rounded-lg text-white focus:outline-none focus:border-orange-500 text-xs"
                    required
                  />
                </div>

                <div>
                  <label className="block text-zinc-300 font-medium mb-1">
                    Target Course Database Name
                  </label>
                  <input
                    type="text"
                    placeholder="e.g. Course Notes & Assignments"
                    value={databaseNameInput}
                    onChange={(e) => setDatabaseNameInput(e.target.value)}
                    className="w-full px-3 py-2 bg-zinc-900 border border-zinc-800 rounded-lg text-white focus:outline-none focus:border-orange-500 text-xs"
                    required
                  />
                </div>

                <div>
                  <div className="flex items-center gap-1 text-zinc-400 mb-1">
                    <Lock className="w-3.5 h-3.5" />
                    <span>Optional: Notion Internal Integration Secret</span>
                  </div>
                  <input
                    type="password"
                    placeholder="secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                    value={apiKeyInput}
                    onChange={(e) => setApiKeyInput(e.target.value)}
                    className="w-full px-3 py-2 bg-zinc-900 border border-zinc-800 rounded-lg text-white placeholder-zinc-600 focus:outline-none focus:border-orange-500 font-mono text-xs"
                  />
                  <p className="text-[10px] text-zinc-500 mt-1">
                    Credentials remain on the server. Leave blank to use integrated preview sync.
                  </p>
                </div>

                <div className="flex gap-2 pt-2">
                  <button
                    type="submit"
                    className="flex-1 py-2.5 bg-orange-600 hover:bg-orange-500 text-white font-semibold rounded-lg transition-all shadow-md text-xs flex items-center justify-center gap-1.5"
                  >
                    <Link2 className="w-3.5 h-3.5" />
                    <span>{workspace.connected ? 'Save Workspace Changes' : 'Connect Notion Workspace'}</span>
                  </button>

                  {workspace.connected && (
                    <button
                      type="button"
                      onClick={handleDisconnectNotion}
                      className="px-3 py-2.5 bg-zinc-900 hover:bg-rose-950/40 text-zinc-400 hover:text-rose-300 border border-zinc-800 rounded-lg transition-colors text-xs flex items-center gap-1"
                    >
                      <Unlink className="w-3.5 h-3.5" />
                      <span>Disconnect</span>
                    </button>
                  )}
                </div>
              </form>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
